project:
  type: website
  output-dir: _site

website:
  title: "Nextflow Crash Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting_started.qmd
        text: Getting Started on Hazel
      - href: tour_of_hazel.qmd
        text: Tour of Hazel
