project:
  type: website
  output-dir: _site

website:
  title: "Nextflow Crash Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: loading_brc_modules.qmd
        text: Loading BRC Modules
      - href: nf_core_pipelines.qmd
        text: nf-core Pipelines
